namespace BackgroundCopyManager3_0
{
    using System;

    public enum __MIDL_IBackgroundCopyError_0001
    {
        BG_ERROR_CONTEXT_NONE,
        BG_ERROR_CONTEXT_UNKNOWN,
        BG_ERROR_CONTEXT_GENERAL_QUEUE_MANAGER,
        BG_ERROR_CONTEXT_QUEUE_MANAGER_NOTIFICATION,
        BG_ERROR_CONTEXT_LOCAL_FILE,
        BG_ERROR_CONTEXT_REMOTE_FILE,
        BG_ERROR_CONTEXT_GENERAL_TRANSPORT,
        BG_ERROR_CONTEXT_REMOTE_APPLICATION
    }
}

